[package]
name = "tests"
version.workspace = true
edition.workspace = true
publish = false

[dev-dependencies]
rom_cache = { path = "../rom-cache" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }

[target.'cfg(loom)'.dev-dependencies]
loom = { workspace = true }

[[test]]
name = "loom_test"
path = "loom_test.rs"

[features]
default = []
