[package]
name = "examples"
version.workspace = true
edition.workspace = true
publish = false

[dev-dependencies]
rom_cache = { path = "../rom-cache" }

[[example]]
name = "example"
path = "example.rs"
required-features = ["nightly"]

[features]
default = []
nightly = ["rom_cache/nightly"]
